### ISSUE TITLE
[Feature]: Delete the GUI application 

### ISSUE THREAD

**Issue by aatwi** [murex/TCR#186]
### Feature Request

We are facing some issues with maintaining the GUI application
- It is lagging behind as we are not updating it
- It makes the release process more complex and slower 
- We are not using it at the moment 

### Feature Description

We want to remove all the code related to the TCR-GUI application from the repository.
To achieve that, we need to do the following: 
- Remove the tcr-gui folder 
- Update GitHub actions 
- Clean the make file  
- remove .goreleaser-gui.yml file
- Update the ReadMe.md by removing all reference to the GUI
- Update the file sonar-project.properties 
- Remove all the "fyne" files from the folder tools/scripts 

In addition to that, we want to merge the tcr-cli and tcr-engine modules.

### Alternatives

- Implement the new features into the GUI
- Not merge the tcr-cli and tcr-engine

### Additional Context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### TODO LIST
- [x] 🤝We want to remove all the code related to the TCR-GUI application from the repository.
   - [x] Remove the tcr-gui folder 
   - [x] Update GitHub actions 
   - [x] Clean the Makefile  
   - [x] remove .goreleaser-gui.yml file
   - [x] Update the ReadMe.md by removing all reference to the GUI
   - [x] Update the file sonar-project.properties 
   - [x] Remove all the "fyne" files from the folder tools/scripts 
   - [x] Remove references to GUI from cobra commands online help
     - [x] Remove references to GUI from commands in cmd package
     - [x] Re-run make doc to update generated md files in doc directory 
- [x] 🤝We want to merge the tcr-cli and tcr-engine modules.
   - [x] Move all code to a single module named src
      - [x] rename tcr-cli dir to src
         - [x] rename dirs
         - [x] rename module name inside tcr-cli/go.mod to just 'tcr'
         - [x] update the makefiles to reflect the change
         - [x] update github actions
         - [x] update the readme
         - [x] update goreleaser.yml
         - [x] update .gitignore
         - [x] update module in tcr-doc
         - [x] update sonar properties
         - [x] test and commit
      - [x] move all code that is in tcr-engine into src
         - [x] make sure tcr-engine dependencies get into the src module definition
         - [x] make sure the rules from tcr-engine makefiles are all in the src one
         - [x] update the top-level makefile
         - [x] make build make test
         - [x] delete the tcr-engine dir and its modules
         - [x] update github actions
         - [x] update the readme
         - [x] update goreleaser.yml
         - [x] update .gitignore
         - [x] update sonar properties
         - [x] update module in tcr-doc
 - [x] Push
- [x] 👆 verify CI works
- [x] 👆 verify Sonar works
- [x] 👆 verify Coveralls works
- [x] 👆 Merge to main
- [x] 👆 Make a new release to verify that go release works
- [x] 👆 Test from a kata to make sure the wrapper still works
