### ISSUE TITLE
[Feature]: Make it easy to manually test the latest TCR sources locally

### ISSUE THREAD

**Issue by philou** [murex/TCR#199]
### Contact Details

philippe.bourgau@murex.com

### Feature Request

When adding new features to TCR, it's a bit cumbersome to test the new tool manually. We usually resort to running TCR from the exemples, with a custom command line.

### Feature Description

Wrap the custom command line in a script.

It would also be nice to be able to easily debug this latest-built tool seamlessly from the IDE.

### Alternatives

- have a custom test dir that is updated with the latest TCR as this one is built
- or have an extra config in the 'examples' dir

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### TODO

- [x] Create an alternate script to run TCR from the test data
- [x] Make it easy to debug from IDE
   - [x] Setup an IntelliJ run config to run TCR
   - [x] Document how to run the same thing from any IDE debugger
   - [x] Learn about alternative ways to debug by attaching to a running go process
- [x] Wrap this in a `make run` target
