### ISSUE TITLE
[Feature]: Mark slowest tests as Slow and use `go test -short` when running tcr on tcr

### ISSUE THREAD

**Issue by philou** [murex/TCR#224]
### Contact Details

philippe.bourgau@murex.com

### Feature Request

TCR can be slow to run on the whole TCR codebase.

### Feature Description

Configure TCR to use `go test -short` when running tests on the whole TCR codebase

Skip slowest tests in short mode.

### Alternatives

- Run TCR only on one packages at a time. This is problematic if our changes impact other packages.
- Use TCR to report slowest tests and add options to configure tests to skip.
- Cross git diff and coverage data to run all but only impacted tests.

### Additional Context

This action came out of the Retro we did on 2023-01-24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### TODO

- [x] Report slowest tests
- [x] Add a markdown memo to know how to report slow tests
- [x] Skip tests that take more than 1s to execute
	- [x] Test_mob_timer_duration_trace_at_startup: 4.03s
	- [x] Test_maven_wrapper_toolchain_returns_ok_when_tests_pass: 3.84s
	- [x] Test_checker_should_return_1_if_one_or_more_warnings: 2.44s
	- [x] Test_maven_wrapper_toolchain_returns_ok_when_build_passes: 2.41s
	- [x] Test_gradle_wrapper_toolchain_returns_ok_when_build_passes: 2.37s
	- [x] Test_mob_timer_should_not_start_in_solo_mode: 2.02s
	- [x] Test_mob_timer_duration_trace_at_startup/duration_2h0m0s: 2.02s
	- [x] Test_mob_timer_duration_trace_at_startup/duration_1m0s: 2.02s
	- [x] Test_gradle_wrapper_toolchain_returns_ok_when_tests_pass: 1.89s
	- [x] Test_checker_should_return_2_if_one_or_more_errors: 1.84s
	- [x] Test_check_remote_access_on_current_repo: 1.72s
	- [x] Test_tcr_print_log: 1.43s
	- [x] Test_main_menu: 1.17s
- [x] Configure tcr to use -short, was already done
- [x] Remove SKIP traces from test execution logs
- [x] Use gotestsum's option to automatically list slow tests in a make target
