### ISSUE TITLE
[Feature][Spike]: Try to speed up one of the slowest tests and try go get it out of the "Slow and Skipped" group

### ISSUE THREAD

**Issue by philou** [murex/TCR#225]
### Contact Details

philippe.bourgau@murex.com

### Feature Request

It is difficult to run TCR on the full TCR code base, because building and running all tests is slow.

### Feature Description

Let's see how we could refactor one of the slowest tests to see if we can make it fast enough to run it all the time. We have many ideas to refactor this:
- refactor to a A-Frame architecture
- use polling instead of sleep timers
- refactor to a more functional style
- provide fake simulators for infrastructure

The goal is really to experiment and discover a technique that we could use in many other situations

### Alternatives

- Run TCR only on one packages at a time. This is problematic if our changes impact other packages.
- Use TCR to report slowest tests and add options to configure tests to skip.
- Cross git diff and coverage data to run all but only impacted tests.

### Additional Context

This action came out of the Retro we did on 2023-01-24.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Candidate tests

```make slow-tests```

```
# Timers, there are waits
github.com/murex/tcr/engine Test_mob_timer_duration_trace_at_startup 4.01s
github.com/murex/tcr/engine Test_mob_timer_should_not_start_in_solo_mode 2.009s
github.com/murex/tcr/engine Test_mob_timer_duration_trace_at_startup/duration_1m0s 2.009s
github.com/murex/tcr/engine Test_mob_timer_duration_trace_at_startup/duration_2h0m0s 2s

# Kind of acceptance tests that call the real toolchains
github.com/murex/tcr/toolchain Test_gradle_wrapper_toolchain_returns_ok_when_build_passes 2.78s
github.com/murex/tcr/toolchain Test_maven_wrapper_toolchain_returns_ok_when_tests_pass 2.61s
github.com/murex/tcr/toolchain Test_maven_wrapper_toolchain_returns_ok_when_build_passes 2.25s
github.com/murex/tcr/toolchain Test_gradle_wrapper_toolchain_returns_ok_when_tests_pass 2.21s

# ?
github.com/murex/tcr/cli Test_main_menu 1.84s

# no test doubles, could be isolated
github.com/murex/tcr/checker Test_checker_should_return_2_if_one_or_more_errors 1.84s
github.com/murex/tcr/checker Test_checker_should_return_1_if_one_or_more_warnings 1.57s

# ?
github.com/murex/tcr/engine Test_tcr_print_log 1.41s

# ?, but might be fixed by faking a git call
github.com/murex/tcr/vcs/git Test_git_log 510ms
```

### TODO

- [x] Have a look at each kind of test to brainstorm ideas
- [x] Analyze: github.com/murex/tcr/engine
   - Find a way to initialize the TCR directly with the fake VCS instead of initializing with real git and then replacing it in the fake. ref: tcr_test line 380
- [x] Analyze: github.com/murex/tcr/toolchain
   - This test calls the exec of Maven and Gradle. It is normal to take that much time
   - To avoid it, we might need to try a Stub that return true or false when called 
- [x] Analyze `github.com/murex/tcr/cli Test_main_menu.`
   - The time is being wasted on retrieving the terminal width. We can use a flag in the package that would disable this call and return a default value. 
- [x] Analyze `github.com/murex/tcr/vcs/git Test_git_log`
  - The test is initializing a new Git instance instead of fake. ref: line 643
- [x] Analyze `github.com/murex/tcr/engine Test_tcr_print_log`
  - Get rid of the `time.Sleep(traceReporterWaitingTime)` in tcr PrintLog function.

#### 2 Options to this spike
- Understand and get rid of the `time.Sleep(traceReporterWaitingTime)` in tcr PrintLog function.
   - Might be interesting to look into that
- Agree on Testing Without Mocks (or/and Cucumber living documentation), and decide where to get started
   - Definitely a discussion to have soon
   - PoC a first functional test with Cucumber / GoDog

#### Quick Wins
- [x] ❌Initialize the TCR directly with the fake VCS instead of initializing with real git and then replacing it in the fake in `github.com/murex/tcr/engine`
  - [x] Remove `Impl` field from get_test_fake
  - [x] ❌ create a new kind of vcs "fake"
     - We did not manage speed up the tests by using a fake git! Profiler was not precise enough, sometimes missleading
- [x] Use a flag in the package that would disable this call and return a default terminal column width in `github.com/murex/tcr/cli Test_main_menu`

### Lessons

- IntelliJ profiler is not super-accurate, maybe small tests are not enough! We said we'll try go-tools benchmarks to see exactly what is happening
- Most of the slowness (and complicatedness of tests) comes from integrating with `bash`, `terminal`, the filesystem, and command lines tools
- We should start to look into defining and moving towards an explicit test strategy
