### ISSUE TITLE
[Feature]: Allow configuration of source and test directories that don't exist

### ISSUE THREAD

**Issue by mengdaming** [murex/TCR#258]
### Contact Details

damien.menanteau@gmail.com

### Feature Request

Currently, TCR reports an error and exits when the configured language directories are missing from the filesystem.

Having the possibility to let TCR run even if some configured source and/or test directories are missing could improve usability and allow to come up with "generic" language configurations that do not require additional tuning when running on components that have slight variations in directory structure.

### Feature Description

- Display a warning instead of exiting on error when a configured source or test directory configured for the language is not present on disk
- TCR should still report an error and exit if no source or test directory is present on disk (there should at least be 1 of each)
- It’s ok if they need to restart TCR in case they create the directory after

### Alternatives

N/A

### Additional Context

N/A

### TODO

- [x] Ignore absent directories mentioned in “watch” settings
   - [x] Display a warning instead of an error in the configuration checker
      - [x] Create a new kind of error that accumulates ‘bogus’ dirs
      - [x] Update file_tree_filter.go findAllMatchingFiles to not systematically return an error
         - [x] Accumulate a list of errors instead of a single error, and continue on next dir
         - [x] Check that dir exists before calling afero.Walk()
      - [x] Update language checker to handle these errors 
   - [x] Stop watching directories that do not exist
      - make sure no warning or error is displayed / happens
      - Do not say “Watching xxx” if xxx does not exist
      - [x] Create a wrapper function around DirsToWatch, that filters out absent dirs, so that language remains indep from OS and filesystem
         - [x] Implement general case
         - [x] bubble up errors
      - [x] Wrap calls to DirsToWatch with this new function
      - [x] Stop TCR in case of error
   - [x] Deal with the case where nothing is watched
     - Current behaviour:
        - tcr check reports warnings (no src/test directories, no matching files found)
        - tcr in driver mode works, but does not watch any directory. As a consequence the TCR cycle will never be triggered
     - Decision: Ignore this case as this is not how TCR is supposed to be used. We just display a warning at startup for every configured directory that cannot be accessed.
   - [x] Add a warning at startup when a watched dir is missing
       - [x] this could be combined with a warning displayed at startup if there is nothing to watch 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
