### ISSUE TITLE
[Feature]: Support "real" TCR that also reverts tests

### ISSUE THREAD

**Issue by philou** [murex/TCR#674]
### Contact Details

philippe.bourgau@gmail.com

### Feature Request

The TCR tool only reverts the code files, and keeps the failing test. The original TCR was also reverting the tests. These 2 behaviors lead to quite different workflow. The original TCR encourages:

- to add "disabled" tests that get "re-disabled" when they fail
- to take even smaller steps, and to use the tidy-first workflow: "Make the change easy, then make the easy change"

### Feature Description

This could be an option to TCR (ex: --also-revert-tests). It could also become the default behavior, and make the current behavior available with an option (ex: --nice)

### Alternatives

An alternative is to completely drop the current behavior, and stick only to the Real TCR.

### Additional Context

I needed this feature on the Baby Steps Golf Kata (https://github.com/philou/kata-babystepsgolf). I ended up reverting to straightforward TCR scripts. I also needed to run the TCR manually (and not systematically on save, as I wanted participants to give a special commit message).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### TODO

- [x] Add a parameter "flavor": taking 2 values: "nice" (current, and default) and "original" (which reverts tests)
  - [x] find a shortcut letter for the command line -> 'f'
  - [x] make commit failures shortcut upper 'F'
  - [x] define the flavor parameter
  - [x] Call the AddFlavorParam
- [x] add and pass down the flavor attribute to the TCR struct
  - [x] add flavor to TCREngine
  - [x] pass the flavor from UI to TCREngine
- [x] Display the flavor in the UI
  - [x] Terminal
  - [x] Angular
    - [x] Transfer Flavor through HTTP
    - [x] Display in in the web frontend
    - [x] Improve wording on web frontend
- [x] Transform flavor from string to enum:
  - [x] flavor -> Variant
  - [x] nice -> relaxed
  - [x] original -> btcr (build && (test && commit || revert)
  - [x] Create an enum 
  - [x] propagate the types from the params
  - [x] add a Name() function to variant type
- [x] in tcr.revert, branch on the 2 variants
  - [x] Add a test around the current source revert, asserting reverted files with VCS fake
    - [x] test that revert was called
    - [x] add both tests and source files
    - [x] make it possible to capture src from test files in the languages
    - [x] assert that only source files are reverted
    - [x] override and add a parameter to initTCREngineWithFakes to pass in an array of file diffs
    - [x] assert that many sources files can be reverted
    - [x] Transform the tests to parametrized tests
  - [x] Rename tcr.srcRevert to tcr.revertSrcOnly
  - [x] implement the btcr variant
    - [x] add tests around btcr
    - [x] implement
- [x] add a 3rd variant: "introspective", which is based on btcr but also commits failures and reverts
  - [x] draw a mermaid diagram to visualize what it will look like
  - [x] add description for introspector variant in variants markdown description file
  - [x] check that it works in the UI and Command Line
  - [x] Add tests for the introspective variant
    - [x] Add a list of received commands in VCS fake so that we can test that we got "commit && revert"
    - [x] Should we update the LastCommand to get the tail of the list instead of keeping it?
    - [x] Unskip the test with "add, commit, rollback, and commit"
  - [x] in tcr.revert, implement the introspective variant
    - [x] implement introspectiveRevert (copied from git commitFailures)
    - [x] make sure we have tests for the commit messages
    - [x] clean up the revert function (currently spanning different levels of abstraction)
  - [x] And what about the error we are ignoring out of introspectiveRevert?
  - [x] Add introspective to the list of variants in the short description for variant parameter
- [x] Reinforce command line argument "-r" so that in only accepts recognized variant names
- [x] remove the "commit failure" option and code
  - [x] remove config/cparam_commit_failure()
  - [x] remove CommitFailures flag from params and related test data builder
  - [x] remove parts that leverage on CommitFailures flag in engine.tcr
  - [x] remove SetCommitOnFail()
    - [x] in trc class
    - [x] in tcr interface
  - [x] remove from checker.check_workflow
- [x] clean up vcs interface and related git/p4 implementations 
- [x] add a link to the workflow picture from the web app session info
- [x] Rename in VCS to map to TCR domain, not that of git:
  - [x] rename Revert into RollbackCommit
  - [x] rename Restore into Revert

| Variants                | TCR                   | VCS (current) | VCS (updated)        | git                    | p4                        |
|-------------------------|-----------------------|---------------|----------------------|------------------------|---------------------------|
| original, BTCR, relaxed | revert(file)          | Restore(file) | RevertLocal(file)    | git checkout HEAD file | p4 reconcile file         |
| introspective           | rollbackLastCommit()? | Revert()      | RollbackLastCommit() | git revert HEAD        | TODO: p4 undo + p4 submit |			 

- [x] Test the introspective revert in practice.
  - [x] Should we add some warning or info traces in introspective mode? No, confirmed that this cannot happen when using introspective variant
  - [x] Tune git revert command call so that it does not auto-commits
- [x] rework checker for TCR workflow configuration
  - [x] rename chech_workflow group to check_variant 
  - [x] add checking of variant value
     - [x] variants btcr, relaxed and introspective should be supported (lowercase or uppercase)
     - [x] variant original should return a "not yet supported" error message
     - [x] all other cases should return an error
  - [x] remove "commit failure" related stuff from checker
- [x] document in readme each of the available variants and what they imply in terms of workflow (explain ref to https://medium.com/@tdeniffel/tcr-variants-test-commit-revert-bf6bd84b17d3)
  - [x] Create visual workflows for each variant
- [x] Remove the "amend" parameter in the VCS.Commit function

### Parking
- [ ] Add feature tests (end to end and/or scoped) use more dependency injection and try "Testing without mocks"
- [ ] Create a Builder for the TCREngine(Fake) because the test factory method is getting complicated (we had to add an extra parameter for the FileDiffs
- [ ] improve the VCS fake? (real mock with check method and better error reporting, ex: fakeVCS.assertFilesWereReverted(count: 2...), currently, we are using the reporter warning to check how many files were reverted
- [ ] improve the reporter fake? (real mock with check method and better error reporting, ex: report.assertWarning... instead of setting up the sniffer then asserting count matches)
- [ ] implement the orginal variant
- [ ] experiment using strong-type variant in the Params

**Comment by mengdaming** [comment]
A note about running TCR manually (and not systematically on save): this part is already available through running `tcr one-shot` subcommand
