### ISSUE TITLE
[Feature]: Add introspective variant for perforce

### ISSUE THREAD

**Issue by mengdaming** [murex/TCR#791]
### Contact Details

damien.menanteau@gmail.com

### Feature Request

Now that TCR supports introspective variant with git, we would like to have the equivalent with perforce

### Feature Description

Add perforce implementation for vcs.RollbackLastCommit()

### Alternatives

Do nothing

### Additional Context

Cf. VCS and git implementation in #674 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### TODO

- [x] add p4 implementation for RollbackCommit(): p4 undo + p4 submit
  - [x] Implement the p4 submit 
  - [x] ask for p4 licenses (ours are revoked)
  - [x] Setup an environment and test
  - [x] Implement the p4 undo 
    - [x]  test the exact command manually
      - `p4 undo @7294695,@7294695` (7294695=changelist number) then we need to submit
    - [x] Understand and document what we have and what we need to do
      - [x] add comments in CreateChangelist method to explain
        - [x] "p4 change -o | p4 change - i" we need the piping to output a cl spec and then to read and create it
        - [x] "change -o" takes all the changed files from the Default changelist and adds them to this new cl
    - [x] Implement it
      - we can rely on the current Commit method to create a new cl, add modified files, and submit
      - what the function needs to do is
        - [x] get the cl to rollback "p4 changes -m1 @<client_name>"
          - [x] fix the missing @
        - [x] undo this cl "p4 undo @<cl>,@<cl>"
  - [x] Verify on real p4 instance 
  - [x] What about emojies not displaying correctly in P4V? what is the necessary config
    - cf. https://portal.perforce.com/s/article/3104
    - [x] Create a new issue to use text instead of emojies, at least in Perforce (TBD)
- [x] Try FizzBuzz?
- [x] Add a note in README about perforce that user should enable "auto mark for edit on file modification"
- [x] Add a note in README about p4ignore: can do `p4 set P4IGNORE=.gitignore`. As TCR adds everything in the diff, you might end up with: binary build files in the depot, or unreadable diff files
